repos:
- repo: https://github.com/asottile/pyupgrade
  rev: "v3.15.0"
  hooks:
  - id: pyupgrade
    args: ["--py39-plus"]
    exclude: ^test_playground/

- repo: https://github.com/hadialqattan/pycln
  rev: "v2.4.0"
  hooks:
  - id: pycln
    args:
    - --all
    include: ^micmac/foregrounds, ^micmac/likelihood, ^micmac/tools, ^micmac/noise
    exclude: ^test_playground/, ^tutorials/, ^micmac/

- repo: https://github.com/PyCQA/isort
  rev: '5.13.2'
  hooks:
  - id: isort
    args:
    - --profile=black
    exclude: ^test_playground/

- repo: https://github.com/psf/black
  rev: '23.12.0'
  hooks:
  - id: black
    args:
    - --line-length=120
    - --skip-string-normalization
    exclude: ^test_playground/

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.5.0'
  hooks:
  - id: trailing-whitespace
    exclude: ^test_playground/
  - id: end-of-file-fixer
    exclude: ^test_playground/
  - id: check-yaml
    exclude: ^test_playground/
  - id: double-quote-string-fixer
    exclude: ^test_playground/
  - id: check-merge-conflict
    exclude: ^test_playground/
  - id: debug-statements
    exclude: ^test_playground/

- repo: https://github.com/pycqa/flake8
  rev: '6.1.0'
  hooks:
  - id: flake8
    name: flake 8 (src)
    args:
    - --max-line-length=120
    # E203 whitespace before ':' (black incompatibility)
    # E731 do not assign a lambda expression, use a def
    - --extend-ignore=E203,E731
    files: ^micmac/
    exclude: .*
