## These are parameters useful to have the tests general and easy to change
## will not be used in the final version of the code

current_directory='validation_chain_spatialvariability_v2/'
MICMAC_directory = '/Users/arizzieri/APC/PhD/cmb_work/comp_sep/Non_param/MICMAC/'
directory_mask = ''
save_directory = '/Users/arizzieri/APC/PhD/cmb_work/comp_sep/Non_param/MICMAC/test_playground/'

seed_realization_input=42
delta_ell=1
reduction_noise = 1
factor_Fisher = 1
relative_treshold = 1e-1
sigma_gap = 20
fgs_model = 'd0s0'
initial_guess_r=1e-4
use_nhits = false
name_mask = ''
use_mask = false
use_preconditioner = false

name_toml = 'corr_fullsky_SO_v1a.toml'
name_file_spv = ''
former_file_ver = ''
file_ver = 'corr_fullsky_SO_v108_v1a'
