## These are parameters useful to have the tests general and easy to change
## will not be used in the final version of the code

current_directory='validation_chain_spatialvariability_v2/'
# MICMAC_directory = '/Users/mag/Documents/PHD1Y/Space_Work/Pixel_non_P2D/MICMAC/'
MICMAC_directory = '/gpfswork/rech/nih/ube74zo/MICMAC/MICMAC/'
directory_mask = "/gpfswork/rech/nih/commun/masks/"
save_directory = ''

seed_realization_input=42
delta_ell=1
reduction_noise = 1
factor_Fisher = 1
relative_treshold = 1e-1
sigma_gap = 20
fgs_model = 'd0s0'
initial_guess_r=1e-4
use_nhits = false
name_mask = ''
use_mask = false
use_preconditioner = true

name_toml = 'corr_fullsky_SO_v2b.toml'
name_file_spv = ''
former_file_ver = ''
file_ver = 'corr_fullsky_SO_v108_v2a'
