## These are parameters useful to have the tests general and easy to change
## will not be used in the final version of the code

current_directory='Paper_runs/'
MICMAC_directory = '/Users/mag/Documents/PHD1Y/Space_Work/Pixel_non_P2D/MICMAC/'
directory_mask = "/Users/mag/Documents/PHD1Y/Masks/"
save_directory = ''
path_trace_jax = ''
path_cov_B_f_r = '/Users/mag/Documents/PHD1Y/Space_Work/Pixel_non_P2D/MICMAC/test_playground/Fake_Fisher_matrix_LiteBIRD.txt'

seed_realization_input=42
delta_ell=1
reduction_noise = 1
factor_Fisher = 1
factor_Fisher_r = 1
relative_treshold = 1e-1
sigma_gap = 0
fgs_model = 'd0s0'
initial_guess_r=1e-2
use_nhits = false
name_mask = 'Planck_mask_fsky_60'
use_mask = true
use_preconditioner = true

name_toml = 'corr_cutsky_LB_r2_v2b.toml' #
name_file_spv = 'params_spv_LB_nside0.yaml'
former_file_ver = ''
file_ver = 'corr_cutsky_LB_d0s0_nside0_v1901_v2b'
