# [Quick_test_parameters]
disable_chex = true
classical_Gibbs = false
biased_version = false
perturbation_eta_covariance = true
use_uncorrelated_patches = false
simultaneous_accept_rate = false
full_sky_correction = false
use_binning=false

# [Data]
save_CMB_chain_maps = false # If true, all the sampled CMB maps which are marginalized over will be saved
save_eta_chain_maps = false # If true, all the sampled eta maps which are marginalized over will be saved

# [Instrument_parameters]
instrument_name = 'LiteBIRD' # Either provide instrument name, then freq_inverse_noise and frequency_array will be taken from fgbuster, 
# or provide expcitely freq_inverse_noise and frequency_array with instrument_name="customized_instrument"
# freq_inverse_noise = []
# frequency_array = []

# [CMB_parameters]
r_true = 1e-2
sample_r_Metropolis = true
sample_C_inv_Wishart = false

# [Problem_parameters]
nside = 64
lmax = 128
nstokes = 2
lmin = 2
n_iter = 8 # Number of iterations for Python estimation of alms
n_components = 3
pos_special_freqs = [0,-1]
indexes_free_Bf = false # Indexes that will be sampled

# [CG_parameters]
limit_iter_cg = 200 #2000 # Maximum number of iterations for the different CGs
limit_iter_cg_eta = 200 # Maximum number of iterations for the CG of eta
tolerance_CG = 1e-6 # Tolerance for the different CGs
atol_CG = 1e-8

# [Metropolis-Hastings-within-Gibbs_parameters]
step_size_r = 1e-3 #1e-4 #1e-5 ???

# [Sampling_parameters]
# overrelax = 0 #-0.995 # Overrelaxation parameter for the sampling
number_iterations_sampling = 200 # Maximum number of iterations for the sampling
number_iterations_done = 0 # Number of iterations already accomplished, in case the chain is resuming from a previous run
seed = 42
