# [Run_settings]
biased_version = false # If true, the biased version of the code will be used and no correction will be applied to the log-likelihood

# [Problem_parameters]
nside = 64
lmax = 128
nstokes = 2
lmin = 2
n_iter = 8 # Number of iterations for Python estimation of alms
n_components = 3
pos_special_freqs = [0,-1]

# [CMB_parameters]
r_true = 1e-2 # True value of r, only used to generate the input CMB maps

# [Instrument_parameters]
instrument_name = 'LiteBIRD'
# Either provide instrument name, then frequency_array and the noise levels to form freq_noise_c_ell and will be taken from fgbuster,
# or provide expcitely freq_noise_c_ell and frequency_array with instrument_name="customized_instrument"
# freq_noise_c_ell = []
# frequency_array = []

# [Metropolis-Hastings_parameters]
# step_size_r = 1e-4
# covariance_B_f = 1e-9

# [Sampling_parameters]
number_iterations_sampling = 1000 # Maximum number of iterations for the sampling
number_iterations_done = 0 # Number of iterations already accomplished, in case the chain is resuming from a previous run
seed = 42

# [Optional_parameters]
disable_chex = true
