## These are parameters useful to have the tests general and easy to change
## will not be used in the final version of the code

current_directory='Paper_runs_v2/'
MICMAC_directory = '/gpfswork/rech/nih/ube74zo/MICMAC/MICMAC/'
# MICMAC_directory = '/Users/mag/Documents/PHD1Y/Space_Work/Pixel_non_P2D/MICMAC/'
directory_mask = "/gpfswork/rech/nih/commun/masks/"
# directory_mask = "/Users/mag/Documents/PHD1Y/Masks/"
save_directory = ''
path_trace_jax = ''
# path_cov_B_f_r = '/Users/mag/Documents/PHD1Y/Space_Work/Pixel_non_P2D/MICMAC/test_playground/Fake_Fisher_matrix_LiteBIRD.txt'
path_cov_B_f_r = '/gpfswork/rech/nih/ube74zo/MICMAC/MICMAC/test_playground/Fake_Fisher_matrix_LiteBIRD.txt'

seed_realization_input=42
seed_realization_CMB = 40

delta_ell = 1

reduction_noise = 1
factor_Fisher = 1
factor_Fisher_r = 1
relative_treshold = 0
sigma_gap = 0
fgs_model = 'd0s0'
initial_guess_r=1e-2
name_mask = ''
use_mask = false
use_preconditioner = true

use_treshold = false
use_nhits = false

use_last_sample = false
save_last_sample = true
stack_former_file_ver = false

name_toml = 'corr_fullsky_SO_r2_v1a.toml'
name_file_spv = ''
file_ver_last_sample = ''
former_file_ver = ''
file_ver = 'corr_fullsky_SO_d0s0_r2_v1a'
