# [Quick_test_parameters]
fullsky_ver = true
slow_ver = false
sample_eta_B_f = true

# [Instrument_parameters]
instrument_name = 'SO_SAT' # Either provide instrument name, then freq_inverse_noise and frequency_array will be taken from fgbuster, 
# or provide expcitely freq_inverse_noise and frequency_array with instrument_name="customized_instrument"
# freq_inverse_noise = []
# frequency_array = []

# [CMB_parameters]
r_true = 0.01
only_select_Bmodes = false
no_Emodes_CMB = false
sample_r_Metropolis = true
sample_C_inv_Wishart = false

# [Problem_parameters]
nside = 64
lmax = 128
nstokes = 2
lmin = 2
n_iter = 8 # Number of iterations for Python estimation of alms
number_components = 3
pos_special_freqs = [0,-1]

# [CG_parameters]
limit_iter_cg = 2000 # Maximum number of iterations for the different CGs
tolerance_CG = 1e-12 # Tolerance for the different CGs

# [Metropolis-Hastings-within-Gibbs_parameters]
n_walkers_Metropolis = 1 # Number of walkers for the MCMC to sample the mixing matrix or r
step_size_B_f = 1e-4
step_size_r = 1e-4 #1e-5 ???
number_steps_sampler_B_f = 100 # Maximum number of steps for the Metropolis-Hasting to sample the mixing matrix
number_steps_sampler_r = 100

# [Sampling_parameters]
number_iterations_sampling = 10 # Maximum number of iterations for the sampling
number_iterations_done = 0 # Number of iterations already accomplished, in case the chain is resuming from a previous run
seed = 0
