# d7s0 with reduced noise !!
reduction_noise = 10
factor_Fisher = 1
relative_treshold = 1e-1
sigma_gap = 10
fgs_model = 'd7s0'
initial_guess_r=1e-8
use_nhits = false
name_mask = "mask_SO_SAT_apodized"
use_mask = true
name_toml = 'corr_cutsky_v1b.toml'
former_file_ver = ''
file_ver = 'corr_cutsky_d7s0_v104_v1b'
