reduction_noise = 1
factor_Fisher = 1
relative_treshold = 1e-1
sigma_gap = 10
fgs_model = 'd0s0'
initial_guess_r=1e-8
use_nhits = false
name_mask = ""
use_mask = false
name_toml = 'corr_fullsky_v1b.toml'
former_file_ver = ''
file_ver = 'corr_fullsky_v104_v1b'
