current_directory = 'validation_chain_v5b/'
MICMAC_directory = '/Users/mag/Documents/PHD1Y/Space_Work/Pixel_non_P2D/MICMAC/'
directory_mask = "/Users/mag/Documents/PHD1Y/Masks/"
save_directory = "//Users/mag/Documents/PHD1Y/Space_Work/Pixel_non_P2D/MICMAC/test_playground/"

delta_ell=1
reduction_noise = 1
factor_Fisher = 1
relative_treshold = 1e-1
sigma_gap = 0
fgs_model = ''
initial_guess_r=1e-3
use_nhits = false
name_mask = "mask_SAT_apodized"
use_mask = false
name_toml = 'invWishart_fullsky_v1b.toml'
former_file_ver = ''
file_ver = 'invWishart_fullsky_v104_v1b'
