## These are parameters useful to have the tests general and easy to change
## will not be used in the final version of the code

current_directory='validation_chain_spatialvariability_v4/'
# MICMAC_directory = '/Users/mag/Documents/PHD1Y/Space_Work/Pixel_non_P2D/MICMAC/'
MICMAC_directory = '/gpfswork/rech/nih/ube74zo/MICMAC/MICMAC/'
# MICMAC_directory = '/work/rizzieri/MICMAC/'
directory_mask = ""
save_directory = ''
path_trace_jax = ''

seed_realization_input=42
delta_ell=1
reduction_noise = 1
factor_Fisher = 1
relative_treshold = 1e-1
sigma_gap = 20
fgs_model = 'd1s1'
initial_guess_r=1e-4
use_nhits = false
name_mask = ''
use_mask = false
use_preconditioner = true

name_toml = 'corr_fullsky_SO_v1b.toml' #
name_file_spv = 'params_spv_SAT_nside1.yaml'
former_file_ver = ''
file_ver = 'corr_fullsky_SO_d1s1_nside1_v1091_v2a'
