# [Quick_test_parameters]
sample_eta_B_f = true
biased_version = true
cheap_save = true
very_cheap_save = true
use_automatic_step_size = false
lognormal_r = false
indexes_free_Bf = false
# disable_chex = false
restrict_to_mask = false
use_old_s_c_sampling = false
# fixed_eta_covariance = false
perturbation_eta_covariance = true
use_binning=false

# [Instrument_parameters]
instrument_name = 'SO_SAT' # Either provide instrument name, then freq_inverse_noise and frequency_array will be taken from fgbuster, 
# or provide expcitely freq_inverse_noise and frequency_array with instrument_name="customized_instrument"
# freq_inverse_noise = []
# frequency_array = []

# [CMB_parameters]
r_true = 1e-2
sample_r_Metropolis = true
sample_C_inv_Wishart = false

# [Problem_parameters]
nside = 64
lmax = 128
nstokes = 2
lmin = 2
n_iter = 8 # Number of iterations for Python estimation of alms
n_components = 3
pos_special_freqs = [0,-1]

# [CG_parameters]
limit_iter_cg = 200 #2000 # Maximum number of iterations for the different CGs
limit_iter_cg_eta = 200 # Maximum number of iterations for the CG of eta
tolerance_CG = 1e-6 # Tolerance for the different CGs

# [Metropolis-Hastings-within-Gibbs_parameters]
step_size_B_f = 1e-3 #1e-4 #1e-6
step_size_r = 1e-3 #1e-4 #1e-5 ???
# number_steps_sampler_B_f = 100 # Maximum number of steps for the Metropolis-Hasting to sample the mixing matrix
# number_steps_sampler_r = 100
num_sample_AM = 100000 # Number of samples for the automated step-size starting procedure
epsilon_cov = 1e-20

# [Sampling_parameters]
# overrelax = 0 #-0.995 # Overrelaxation parameter for the sampling
number_iterations_sampling = 2000 # Maximum number of iterations for the sampling
number_iterations_done = 0 # Number of iterations already accomplished, in case the chain is resuming from a previous run
seed = 42
