current_directory='validation_chain_v9_JZ/'
MICMAC_directory = '/Users/mag/Documents/PHD1Y/Space_Work/Pixel_non_P2D/MICMAC/'
directory_mask = "/Users/mag/Documents/PHD1Y/Masks/"
save_directory = "/Users/mag/Documents/PHD1Y/Space_Work/Pixel_non_P2D/MICMAC/test_playground/"

seed_realization_input=42
delta_ell=1
reduction_noise = 1
factor_Fisher = 1
relative_treshold = 1e-1
sigma_gap = 20
fgs_model = 'd0s0'
initial_guess_r=1e-3
use_nhits = false
name_mask = ""
use_mask = false
name_toml = 'test_corr_fullsky_v0a.toml'
former_file_ver = ''
# file_ver = 'corr_fullsky_v104_v1b_gpu'
file_ver = 'test_corr_fullsky_v1a'
